# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlbumGroupEnum(object):

    """Implementation of the 'AlbumGroup' enum.

    This field describes the relationship between the artist and the album.

    Attributes:
        ALBUM: TODO: type description here.
        SINGLE: TODO: type description here.
        COMPILATION: TODO: type description here.
        APPEARS_ON: TODO: type description here.

    """
    ALBUM = 'album'

    SINGLE = 'single'

    COMPILATION = 'compilation'

    APPEARS_ON = 'appears_on'

