# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlbumTypeEnum(object):

    """Implementation of the 'AlbumType' enum.

    The type of the album.

    Attributes:
        ALBUM: TODO: type description here.
        SINGLE: TODO: type description here.
        COMPILATION: TODO: type description here.

    """
    ALBUM = 'album'

    SINGLE = 'single'

    COMPILATION = 'compilation'

