# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.models.cursor_paging_simplified_artist_object import CursorPagingSimplifiedArtistObject


class CursorPagedArtists(object):

    """Implementation of the 'CursorPagedArtists' model.

    TODO: type model description here.

    Attributes:
        artists (CursorPagingSimplifiedArtistObject): TODO: type description
            here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "artists": 'artists'
    }

    def __init__(self,
                 artists=None):
        """Constructor for the CursorPagedArtists class"""

        # Initialize members of the class
        self.artists = artists 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        artists = CursorPagingSimplifiedArtistObject.from_dictionary(dictionary.get('artists')) if dictionary.get('artists') else None
        # Return an object of this model
        return cls(artists)
