# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class ExternalIdObject(object):

    """Implementation of the 'ExternalIdObject' model.

    TODO: type model description here.

    Attributes:
        isrc (str): [International Standard Recording
            Code](http://en.wikipedia.org/wiki/International_Standard_Recording
            _Code)
        ean (str): [International Article
            Number](http://en.wikipedia.org/wiki/International_Article_Number_%
            28EAN%29)
        upc (str): [Universal Product
            Code](http://en.wikipedia.org/wiki/Universal_Product_Code)

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "isrc": 'isrc',
        "ean": 'ean',
        "upc": 'upc'
    }

    _optionals = [
        'isrc',
        'ean',
        'upc',
    ]

    def __init__(self,
                 isrc=APIHelper.SKIP,
                 ean=APIHelper.SKIP,
                 upc=APIHelper.SKIP):
        """Constructor for the ExternalIdObject class"""

        # Initialize members of the class
        if isrc is not APIHelper.SKIP:
            self.isrc = isrc 
        if ean is not APIHelper.SKIP:
            self.ean = ean 
        if upc is not APIHelper.SKIP:
            self.upc = upc 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        isrc = dictionary.get("isrc") if dictionary.get("isrc") else APIHelper.SKIP
        ean = dictionary.get("ean") if dictionary.get("ean") else APIHelper.SKIP
        upc = dictionary.get("upc") if dictionary.get("upc") else APIHelper.SKIP
        # Return an object of this model
        return cls(isrc,
                   ean,
                   upc)
