# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class ExternalUrlObject(object):

    """Implementation of the 'ExternalUrlObject' model.

    TODO: type model description here.

    Attributes:
        spotify (str): The [Spotify
            URL](/documentation/web-api/concepts/spotify-uris-ids) for the
            object.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "spotify": 'spotify'
    }

    _optionals = [
        'spotify',
    ]

    def __init__(self,
                 spotify=APIHelper.SKIP):
        """Constructor for the ExternalUrlObject class"""

        # Initialize members of the class
        if spotify is not APIHelper.SKIP:
            self.spotify = spotify 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        spotify = dictionary.get("spotify") if dictionary.get("spotify") else APIHelper.SKIP
        # Return an object of this model
        return cls(spotify)
