# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ImageObject(object):

    """Implementation of the 'ImageObject' model.

    TODO: type model description here.

    Attributes:
        url (str): The source URL of the image.
        height (int): The image height in pixels.
        width (int): The image width in pixels.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": 'url',
        "height": 'height',
        "width": 'width'
    }

    _nullables = [
        'height',
        'width',
    ]

    def __init__(self,
                 url=None,
                 height=None,
                 width=None):
        """Constructor for the ImageObject class"""

        # Initialize members of the class
        self.url = url 
        self.height = height 
        self.width = width 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        url = dictionary.get("url") if dictionary.get("url") else None
        height = dictionary.get("height") if dictionary.get("height") else None
        width = dictionary.get("width") if dictionary.get("width") else None
        # Return an object of this model
        return cls(url,
                   height,
                   width)
