# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ItemTypeEnum(object):

    """Implementation of the 'Item type' enum.

    TODO: type enum description here.

    Attributes:
        ALBUM: TODO: type description here.
        ARTIST: TODO: type description here.
        PLAYLIST: TODO: type description here.
        TRACK: TODO: type description here.
        SHOW: TODO: type description here.
        EPISODE: TODO: type description here.
        AUDIOBOOK: TODO: type description here.

    """
    ALBUM = 'album'

    ARTIST = 'artist'

    PLAYLIST = 'playlist'

    TRACK = 'track'

    SHOW = 'show'

    EPISODE = 'episode'

    AUDIOBOOK = 'audiobook'

