# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ItemType2Enum(object):

    """Implementation of the 'Item Type2' enum.

    The ID type.

    Attributes:
        ARTIST: TODO: type description here.
        USER: TODO: type description here.

    """
    ARTIST = 'artist'

    USER = 'user'

