# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ItemType3Enum(object):

    """Implementation of the 'Item Type3' enum.

    The ID type: either `artist` or `user`.

    Attributes:
        ARTIST: TODO: type description here.
        USER: TODO: type description here.

    """
    ARTIST = 'artist'

    USER = 'user'

