# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ItemType1Enum(object):

    """Implementation of the 'Item Type1' enum.

    The ID type: currently only `artist` is supported.

    Attributes:
        ARTIST: TODO: type description here.

    """
    ARTIST = 'artist'

