# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.models.audiobook_object import AudiobookObject


class ManyAudiobooks(object):

    """Implementation of the 'ManyAudiobooks' model.

    TODO: type model description here.

    Attributes:
        audiobooks (List[AudiobookObject]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "audiobooks": 'audiobooks'
    }

    def __init__(self,
                 audiobooks=None):
        """Constructor for the ManyAudiobooks class"""

        # Initialize members of the class
        self.audiobooks = audiobooks 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        audiobooks = None
        if dictionary.get('audiobooks') is not None:
            audiobooks = [AudiobookObject.from_dictionary(x) for x in dictionary.get('audiobooks')]
        # Return an object of this model
        return cls(audiobooks)
