# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.models.device_object import DeviceObject


class ManyDevices(object):

    """Implementation of the 'ManyDevices' model.

    TODO: type model description here.

    Attributes:
        devices (List[DeviceObject]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "devices": 'devices'
    }

    def __init__(self,
                 devices=None):
        """Constructor for the ManyDevices class"""

        # Initialize members of the class
        self.devices = devices 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        devices = None
        if dictionary.get('devices') is not None:
            devices = [DeviceObject.from_dictionary(x) for x in dictionary.get('devices')]
        # Return an object of this model
        return cls(devices)
