# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.models.album_object import AlbumObject


class ManyAlbums(object):

    """Implementation of the 'ManyAlbums' model.

    TODO: type model description here.

    Attributes:
        albums (List[AlbumObject]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "albums": 'albums'
    }

    def __init__(self,
                 albums=None):
        """Constructor for the ManyAlbums class"""

        # Initialize members of the class
        self.albums = albums 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        albums = None
        if dictionary.get('albums') is not None:
            albums = [AlbumObject.from_dictionary(x) for x in dictionary.get('albums')]
        # Return an object of this model
        return cls(albums)
