# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.models.track_object import TrackObject


class ManyTracks(object):

    """Implementation of the 'ManyTracks' model.

    TODO: type model description here.

    Attributes:
        tracks (List[TrackObject]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tracks": 'tracks'
    }

    def __init__(self,
                 tracks=None):
        """Constructor for the ManyTracks class"""

        # Initialize members of the class
        self.tracks = tracks 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        tracks = None
        if dictionary.get('tracks') is not None:
            tracks = [TrackObject.from_dictionary(x) for x in dictionary.get('tracks')]
        # Return an object of this model
        return cls(tracks)
