# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class Markets(object):

    """Implementation of the 'Markets' model.

    TODO: type model description here.

    Attributes:
        markets (List[str]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "markets": 'markets'
    }

    _optionals = [
        'markets',
    ]

    def __init__(self,
                 markets=APIHelper.SKIP):
        """Constructor for the Markets class"""

        # Initialize members of the class
        if markets is not APIHelper.SKIP:
            self.markets = markets 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        markets = dictionary.get("markets") if dictionary.get("markets") else APIHelper.SKIP
        # Return an object of this model
        return cls(markets)
