# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReasonEnum(object):

    """Implementation of the 'Reason' enum.

    The reason for the restriction. Albums may be restricted if the content is
    not available in a given market, to the user's subscription type, or when
    the user's account is set to not play explicit content.
    Additional reasons may be added in the future.

    Attributes:
        MARKET: TODO: type description here.
        PRODUCT: TODO: type description here.
        EXPLICIT: TODO: type description here.

    """
    MARKET = 'market'

    PRODUCT = 'product'

    EXPLICIT = 'explicit'

