# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReleaseDatePrecisionEnum(object):

    """Implementation of the 'ReleaseDatePrecision' enum.

    The precision with which `release_date` value is known.

    Attributes:
        YEAR: TODO: type description here.
        MONTH: TODO: type description here.
        DAY: TODO: type description here.

    """
    YEAR = 'year'

    MONTH = 'month'

    DAY = 'day'

