# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class ResumePointObject(object):

    """Implementation of the 'ResumePointObject' model.

    TODO: type model description here.

    Attributes:
        fully_played (bool): Whether or not the episode has been fully played
            by the user.
        resume_position_ms (int): The user's most recent position in the
            episode in milliseconds.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fully_played": 'fully_played',
        "resume_position_ms": 'resume_position_ms'
    }

    _optionals = [
        'fully_played',
        'resume_position_ms',
    ]

    def __init__(self,
                 fully_played=APIHelper.SKIP,
                 resume_position_ms=APIHelper.SKIP):
        """Constructor for the ResumePointObject class"""

        # Initialize members of the class
        if fully_played is not APIHelper.SKIP:
            self.fully_played = fully_played 
        if resume_position_ms is not APIHelper.SKIP:
            self.resume_position_ms = resume_position_ms 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fully_played = dictionary.get("fully_played") if "fully_played" in dictionary.keys() else APIHelper.SKIP
        resume_position_ms = dictionary.get("resume_position_ms") if dictionary.get("resume_position_ms") else APIHelper.SKIP
        # Return an object of this model
        return cls(fully_played,
                   resume_position_ms)
