# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type2Enum(object):

    """Implementation of the 'Type2' enum.

    The object type.

    Attributes:
        ALBUM: TODO: type description here.

    """
    ALBUM = 'album'

