# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type4Enum(object):

    """Implementation of the 'Type4' enum.

    The object type.

    Attributes:
        USER: TODO: type description here.

    """
    USER = 'user'

