# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type7Enum(object):

    """Implementation of the 'Type7' enum.

    The object type.

    Attributes:
        SHOW: TODO: type description here.

    """
    SHOW = 'show'

