# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type3Enum(object):

    """Implementation of the 'Type3' enum.

    The object type: "track".

    Attributes:
        TRACK: TODO: type description here.

    """
    TRACK = 'track'

