# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type8Enum(object):

    """Implementation of the 'Type8' enum.

    The object type.

    Attributes:
        EPISODE: TODO: type description here.

    """
    EPISODE = 'episode'

