# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type9Enum(object):

    """Implementation of the 'Type9' enum.

    The object type.

    Attributes:
        AUDIOBOOK: TODO: type description here.

    """
    AUDIOBOOK = 'audiobook'

