# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type6Enum(object):

    """Implementation of the 'Type6' enum.

    The object type.

    Attributes:
        AUDIO_FEATURES: TODO: type description here.

    """
    AUDIO_FEATURES = 'audio_features'

