# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    The object type.

    Attributes:
        ARTIST: TODO: type description here.

    """
    ARTIST = 'artist'

